# ------------------------- Pre-commit -------------------------
# uv run pre-commit install
# uv run pre-commit run --files class.ipynb
# uv run pre-commit run --all-files
# git commit -m 'commit msg' --no-verify

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        language: system
        entry: uv
        args:
          - run
          - ruff
          - check
          - --select=E,W,F,I,C90,PLR,B,SIM,UP,RUF
          - --ignore=E731
          - --line-length=120
          - --fix
          - --no-cache
        files: \.(py|pyi|ipynb)$

      - id: ruff-format
        name: Ruff format
        language: system
        entry: uv
        args:
          - run
          - ruff
          - format
          - --line-length=120
          - --no-cache
        files: \.(py|pyi|ipynb)$

      - id: md-format
        name: Markdown format
        language: system
        entry: uv
        args:
          - run
          - md-format.py
        files: \.md$
